<?php
/**
 * SessionApi
 * PHP version 5
 *
 * @category Class
 * @package  Emonsite
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API E-monsite
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: alpha
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Emonsite\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Emonsite\ApiException;
use Emonsite\Configuration;
use Emonsite\HeaderSelector;
use Emonsite\ObjectSerializer;

/**
 * SessionApi Class Doc Comment
 *
 * @category Class
 * @package  Emonsite
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SessionApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getSessionCollection
     *
     * Retrieves the collection of SessionOutputDto resources.
     *
     * @param  string $user_ip user_ip (optional)
     * @param  string $user user (optional)
     * @param  string[] $user user (optional)
     * @param  string $hit_before hit_before (optional)
     * @param  string $hit_strictly_before hit_strictly_before (optional)
     * @param  string $hit_after hit_after (optional)
     * @param  string $hit_strictly_after hit_strictly_after (optional)
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $items_per_page The number of items per page (optional, default to 30)
     *
     * @throws \Emonsite\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Emonsite\Models\InlineResponse20023
     */
    public function getSessionCollection($user_ip = null, $user = null, $user = null, $hit_before = null, $hit_strictly_before = null, $hit_after = null, $hit_strictly_after = null, $page = '1', $items_per_page = '30')
    {
        list($response) = $this->getSessionCollectionWithHttpInfo($user_ip, $user, $user, $hit_before, $hit_strictly_before, $hit_after, $hit_strictly_after, $page, $items_per_page);
        return $response;
    }

    /**
     * Operation getSessionCollectionWithHttpInfo
     *
     * Retrieves the collection of SessionOutputDto resources.
     *
     * @param  string $user_ip (optional)
     * @param  string $user (optional)
     * @param  string[] $user (optional)
     * @param  string $hit_before (optional)
     * @param  string $hit_strictly_before (optional)
     * @param  string $hit_after (optional)
     * @param  string $hit_strictly_after (optional)
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $items_per_page The number of items per page (optional, default to 30)
     *
     * @throws \Emonsite\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Emonsite\Models\InlineResponse20023, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSessionCollectionWithHttpInfo($user_ip = null, $user = null, $user = null, $hit_before = null, $hit_strictly_before = null, $hit_after = null, $hit_strictly_after = null, $page = '1', $items_per_page = '30')
    {
        $returnType = '\Emonsite\Models\InlineResponse20023';
        $request = $this->getSessionCollectionRequest($user_ip, $user, $user, $hit_before, $hit_strictly_before, $hit_after, $hit_strictly_after, $page, $items_per_page);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Emonsite\Models\InlineResponse20023',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSessionCollectionAsync
     *
     * Retrieves the collection of SessionOutputDto resources.
     *
     * @param  string $user_ip (optional)
     * @param  string $user (optional)
     * @param  string[] $user (optional)
     * @param  string $hit_before (optional)
     * @param  string $hit_strictly_before (optional)
     * @param  string $hit_after (optional)
     * @param  string $hit_strictly_after (optional)
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $items_per_page The number of items per page (optional, default to 30)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSessionCollectionAsync($user_ip = null, $user = null, $user = null, $hit_before = null, $hit_strictly_before = null, $hit_after = null, $hit_strictly_after = null, $page = '1', $items_per_page = '30')
    {
        return $this->getSessionCollectionAsyncWithHttpInfo($user_ip, $user, $user, $hit_before, $hit_strictly_before, $hit_after, $hit_strictly_after, $page, $items_per_page)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSessionCollectionAsyncWithHttpInfo
     *
     * Retrieves the collection of SessionOutputDto resources.
     *
     * @param  string $user_ip (optional)
     * @param  string $user (optional)
     * @param  string[] $user (optional)
     * @param  string $hit_before (optional)
     * @param  string $hit_strictly_before (optional)
     * @param  string $hit_after (optional)
     * @param  string $hit_strictly_after (optional)
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $items_per_page The number of items per page (optional, default to 30)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSessionCollectionAsyncWithHttpInfo($user_ip = null, $user = null, $user = null, $hit_before = null, $hit_strictly_before = null, $hit_after = null, $hit_strictly_after = null, $page = '1', $items_per_page = '30')
    {
        $returnType = '\Emonsite\Models\InlineResponse20023';
        $request = $this->getSessionCollectionRequest($user_ip, $user, $user, $hit_before, $hit_strictly_before, $hit_after, $hit_strictly_after, $page, $items_per_page);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSessionCollection'
     *
     * @param  string $user_ip (optional)
     * @param  string $user (optional)
     * @param  string[] $user (optional)
     * @param  string $hit_before (optional)
     * @param  string $hit_strictly_before (optional)
     * @param  string $hit_after (optional)
     * @param  string $hit_strictly_after (optional)
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $items_per_page The number of items per page (optional, default to 30)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getSessionCollectionRequest($user_ip = null, $user = null, $user = null, $hit_before = null, $hit_strictly_before = null, $hit_after = null, $hit_strictly_after = null, $page = '1', $items_per_page = '30')
    {

        $resourcePath = '/sessions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($user_ip !== null) {
            $queryParams['userIp'] = ObjectSerializer::toQueryValue($user_ip, null);
        }
        // query params
        if ($user !== null) {
            $queryParams['user'] = ObjectSerializer::toQueryValue($user, null);
        }
        // query params
        if (is_array($user)) {
            $user = ObjectSerializer::serializeCollection($user, 'multi', true);
        }
        if ($user !== null) {
            $queryParams['user[]'] = ObjectSerializer::toQueryValue($user, null);
        }
        // query params
        if ($hit_before !== null) {
            $queryParams['hit[before]'] = ObjectSerializer::toQueryValue($hit_before, null);
        }
        // query params
        if ($hit_strictly_before !== null) {
            $queryParams['hit[strictly_before]'] = ObjectSerializer::toQueryValue($hit_strictly_before, null);
        }
        // query params
        if ($hit_after !== null) {
            $queryParams['hit[after]'] = ObjectSerializer::toQueryValue($hit_after, null);
        }
        // query params
        if ($hit_strictly_after !== null) {
            $queryParams['hit[strictly_after]'] = ObjectSerializer::toQueryValue($hit_strictly_after, null);
        }
        // query params
        if ($page !== null) {
            $queryParams['page'] = ObjectSerializer::toQueryValue($page, null);
        }
        // query params
        if ($items_per_page !== null) {
            $queryParams['itemsPerPage'] = ObjectSerializer::toQueryValue($items_per_page, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/ld+json', 'application/json', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/ld+json', 'application/json', 'text/html'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSessionItem
     *
     * Retrieves a SessionOutputDto resource.
     *
     * @param  string $id id (required)
     *
     * @throws \Emonsite\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Emonsite\Models\Session1bc7a372e0caf630efd366b7299c4bd2Jsonld
     */
    public function getSessionItem($id)
    {
        list($response) = $this->getSessionItemWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation getSessionItemWithHttpInfo
     *
     * Retrieves a SessionOutputDto resource.
     *
     * @param  string $id (required)
     *
     * @throws \Emonsite\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Emonsite\Models\Session1bc7a372e0caf630efd366b7299c4bd2Jsonld, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSessionItemWithHttpInfo($id)
    {
        $returnType = '\Emonsite\Models\Session1bc7a372e0caf630efd366b7299c4bd2Jsonld';
        $request = $this->getSessionItemRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Emonsite\Models\Session1bc7a372e0caf630efd366b7299c4bd2Jsonld',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSessionItemAsync
     *
     * Retrieves a SessionOutputDto resource.
     *
     * @param  string $id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSessionItemAsync($id)
    {
        return $this->getSessionItemAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSessionItemAsyncWithHttpInfo
     *
     * Retrieves a SessionOutputDto resource.
     *
     * @param  string $id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSessionItemAsyncWithHttpInfo($id)
    {
        $returnType = '\Emonsite\Models\Session1bc7a372e0caf630efd366b7299c4bd2Jsonld';
        $request = $this->getSessionItemRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSessionItem'
     *
     * @param  string $id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getSessionItemRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getSessionItem'
            );
        }

        $resourcePath = '/sessions/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/ld+json', 'application/json', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/ld+json', 'application/json', 'text/html'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
