<?php
/**
 * EcoAdvicesConfigJsonldTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EmonsiteApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API E-monsite
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: alpha
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EmonsiteApi;

/**
 * EcoAdvicesConfigJsonldTest Class Doc Comment
 *
 * @category    Class
 * @description EcoAdvicesConfigJsonld
 * @package     EmonsiteApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EcoAdvicesConfigJsonldTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EcoAdvicesConfigJsonld"
     */
    public function testEcoAdvicesConfigJsonld()
    {
    }

    /**
     * Test attribute "context"
     */
    public function testPropertyContext()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "site"
     */
    public function testPropertySite()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "google_config"
     */
    public function testPropertyGoogleConfig()
    {
    }

    /**
     * Test attribute "avis_verifies_raw_config"
     */
    public function testPropertyAvisVerifiesRawConfig()
    {
    }

    /**
     * Test attribute "econfiance_config"
     */
    public function testPropertyEconfianceConfig()
    {
    }

    /**
     * Test attribute "add_dt"
     */
    public function testPropertyAddDt()
    {
    }

    /**
     * Test attribute "upd_dt"
     */
    public function testPropertyUpdDt()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "add_user_id"
     */
    public function testPropertyAddUserId()
    {
    }

    /**
     * Test attribute "upd_user_id"
     */
    public function testPropertyUpdUserId()
    {
    }
}
