<?php
/**
 * LegalJsonldTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Emonsite
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API E-monsite
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: alpha
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Emonsite;

/**
 * LegalJsonldTest Class Doc Comment
 *
 * @category    Class
 * @description LegalJsonld
 * @package     Emonsite
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LegalJsonldTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LegalJsonld"
     */
    public function testLegalJsonld()
    {
    }

    /**
     * Test attribute "context"
     */
    public function testPropertyContext()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "legal_mention_active"
     */
    public function testPropertyLegalMentionActive()
    {
    }

    /**
     * Test attribute "legalform"
     */
    public function testPropertyLegalform()
    {
    }

    /**
     * Test attribute "headquarter"
     */
    public function testPropertyHeadquarter()
    {
    }

    /**
     * Test attribute "capital"
     */
    public function testPropertyCapital()
    {
    }

    /**
     * Test attribute "legalname"
     */
    public function testPropertyLegalname()
    {
    }

    /**
     * Test attribute "boss_legalname"
     */
    public function testPropertyBossLegalname()
    {
    }

    /**
     * Test attribute "firstname"
     */
    public function testPropertyFirstname()
    {
    }

    /**
     * Test attribute "lastname"
     */
    public function testPropertyLastname()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "rcs"
     */
    public function testPropertyRcs()
    {
    }

    /**
     * Test attribute "cgu_active"
     */
    public function testPropertyCguActive()
    {
    }

    /**
     * Test attribute "retraction_active"
     */
    public function testPropertyRetractionActive()
    {
    }

    /**
     * Test attribute "cookie_active"
     */
    public function testPropertyCookieActive()
    {
    }

    /**
     * Test attribute "privacy_policy_active"
     */
    public function testPropertyPrivacyPolicyActive()
    {
    }

    /**
     * Test attribute "cookies"
     */
    public function testPropertyCookies()
    {
    }

    /**
     * Test attribute "custom_cookies"
     */
    public function testPropertyCustomCookies()
    {
    }

    /**
     * Test attribute "cookie"
     */
    public function testPropertyCookie()
    {
    }

    /**
     * Test attribute "cgu_page"
     */
    public function testPropertyCguPage()
    {
    }

    /**
     * Test attribute "cgv_page"
     */
    public function testPropertyCgvPage()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "site"
     */
    public function testPropertySite()
    {
    }

    /**
     * Test attribute "add_dt"
     */
    public function testPropertyAddDt()
    {
    }

    /**
     * Test attribute "upd_dt"
     */
    public function testPropertyUpdDt()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "add_user_id"
     */
    public function testPropertyAddUserId()
    {
    }

    /**
     * Test attribute "upd_user_id"
     */
    public function testPropertyUpdUserId()
    {
    }

    /**
     * Test attribute "versions"
     */
    public function testPropertyVersions()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "default_lang"
     */
    public function testPropertyDefaultLang()
    {
    }

    /**
     * Test attribute "version_by_lang"
     */
    public function testPropertyVersionByLang()
    {
    }
}
