<?php
/**
 * PageVJsonldTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Emonsite
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API E-monsite
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: alpha
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Emonsite;

/**
 * PageVJsonldTest Class Doc Comment
 *
 * @category    Class
 * @description PageVJsonld
 * @package     Emonsite
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PageVJsonldTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PageVJsonld"
     */
    public function testPageVJsonld()
    {
    }

    /**
     * Test attribute "context"
     */
    public function testPropertyContext()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "title_in_blocks"
     */
    public function testPropertyTitleInBlocks()
    {
    }

    /**
     * Test attribute "titlemenu"
     */
    public function testPropertyTitlemenu()
    {
    }

    /**
     * Test attribute "lang"
     */
    public function testPropertyLang()
    {
    }

    /**
     * Test attribute "item"
     */
    public function testPropertyItem()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "seo_uri"
     */
    public function testPropertySeoUri()
    {
    }

    /**
     * Test attribute "seo_title"
     */
    public function testPropertySeoTitle()
    {
    }

    /**
     * Test attribute "seo_h1"
     */
    public function testPropertySeoH1()
    {
    }

    /**
     * Test attribute "seo_keywords"
     */
    public function testPropertySeoKeywords()
    {
    }

    /**
     * Test attribute "seo_description"
     */
    public function testPropertySeoDescription()
    {
    }

    /**
     * Test attribute "seo_image"
     */
    public function testPropertySeoImage()
    {
    }

    /**
     * Test attribute "seo_additional_meta"
     */
    public function testPropertySeoAdditionalMeta()
    {
    }

    /**
     * Test attribute "seo_no_index"
     */
    public function testPropertySeoNoIndex()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
    }

    /**
     * Test attribute "previewable_content"
     */
    public function testPropertyPreviewableContent()
    {
    }
}
