<?php
/**
 * UserDomainJsonldTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EmonsiteApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API E-monsite
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: alpha
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EmonsiteApi;

/**
 * UserDomainJsonldTest Class Doc Comment
 *
 * @category    Class
 * @description UserDomainJsonld
 * @package     EmonsiteApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserDomainJsonldTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserDomainJsonld"
     */
    public function testUserDomainJsonld()
    {
    }

    /**
     * Test attribute "context"
     */
    public function testPropertyContext()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "mail_server_id"
     */
    public function testPropertyMailServerId()
    {
    }

    /**
     * Test attribute "domain"
     */
    public function testPropertyDomain()
    {
    }

    /**
     * Test attribute "auth_code"
     */
    public function testPropertyAuthCode()
    {
    }

    /**
     * Test attribute "registrar"
     */
    public function testPropertyRegistrar()
    {
    }

    /**
     * Test attribute "registration_date"
     */
    public function testPropertyRegistrationDate()
    {
    }

    /**
     * Test attribute "expiration_date"
     */
    public function testPropertyExpirationDate()
    {
    }

    /**
     * Test attribute "service_subscription_date"
     */
    public function testPropertyServiceSubscriptionDate()
    {
    }

    /**
     * Test attribute "service_renewal_date"
     */
    public function testPropertyServiceRenewalDate()
    {
    }

    /**
     * Test attribute "service_expiration_date"
     */
    public function testPropertyServiceExpirationDate()
    {
    }

    /**
     * Test attribute "registration_dt_b"
     */
    public function testPropertyRegistrationDtB()
    {
    }

    /**
     * Test attribute "expiration_dt_b"
     */
    public function testPropertyExpirationDtB()
    {
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "nichandle"
     */
    public function testPropertyNichandle()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "firstname"
     */
    public function testPropertyFirstname()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "zip"
     */
    public function testPropertyZip()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "fax"
     */
    public function testPropertyFax()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "lang"
     */
    public function testPropertyLang()
    {
    }

    /**
     * Test attribute "organisation"
     */
    public function testPropertyOrganisation()
    {
    }

    /**
     * Test attribute "legalname"
     */
    public function testPropertyLegalname()
    {
    }

    /**
     * Test attribute "legalnumber"
     */
    public function testPropertyLegalnumber()
    {
    }

    /**
     * Test attribute "birthdate"
     */
    public function testPropertyBirthdate()
    {
    }

    /**
     * Test attribute "birthcountry"
     */
    public function testPropertyBirthcountry()
    {
    }

    /**
     * Test attribute "birthcity"
     */
    public function testPropertyBirthcity()
    {
    }

    /**
     * Test attribute "legalform"
     */
    public function testPropertyLegalform()
    {
    }

    /**
     * Test attribute "birthdepartement"
     */
    public function testPropertyBirthdepartement()
    {
    }

    /**
     * Test attribute "afnicident"
     */
    public function testPropertyAfnicident()
    {
    }

    /**
     * Test attribute "method"
     */
    public function testPropertyMethod()
    {
    }

    /**
     * Test attribute "onerror"
     */
    public function testPropertyOnerror()
    {
    }

    /**
     * Test attribute "support_comment"
     */
    public function testPropertySupportComment()
    {
    }

    /**
     * Test attribute "awelty_admin"
     */
    public function testPropertyAweltyAdmin()
    {
    }

    /**
     * Test attribute "ping_dt"
     */
    public function testPropertyPingDt()
    {
    }

    /**
     * Test attribute "business"
     */
    public function testPropertyBusiness()
    {
    }

    /**
     * Test attribute "autorenew"
     */
    public function testPropertyAutorenew()
    {
    }

    /**
     * Test attribute "command_id"
     */
    public function testPropertyCommandId()
    {
    }

    /**
     * Test attribute "zimbra_server"
     */
    public function testPropertyZimbraServer()
    {
    }

    /**
     * Test attribute "companynationalidentificationnumber"
     */
    public function testPropertyCompanynationalidentificationnumber()
    {
    }

    /**
     * Test attribute "nationalidentificationnumber"
     */
    public function testPropertyNationalidentificationnumber()
    {
    }

    /**
     * Test attribute "vat"
     */
    public function testPropertyVat()
    {
    }

    /**
     * Test attribute "check_auto_renew_after"
     */
    public function testPropertyCheckAutoRenewAfter()
    {
    }

    /**
     * Test attribute "domain_errors"
     */
    public function testPropertyDomainErrors()
    {
    }

    /**
     * Test attribute "mail_aliases"
     */
    public function testPropertyMailAliases()
    {
    }

    /**
     * Test attribute "mailboxes"
     */
    public function testPropertyMailboxes()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "add_dt"
     */
    public function testPropertyAddDt()
    {
    }

    /**
     * Test attribute "upd_dt"
     */
    public function testPropertyUpdDt()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "creator"
     */
    public function testPropertyCreator()
    {
    }

    /**
     * Test attribute "updator"
     */
    public function testPropertyUpdator()
    {
    }
}
