<?php
/**
 * BrandApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  EmonsiteApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API E-monsite
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: alpha
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EmonsiteApi\Test\Api;

use \EmonsiteApi\Configuration;
use \EmonsiteApi\ApiException;
use \EmonsiteApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BrandApiTest Class Doc Comment
 *
 * @category Class
 * @package  EmonsiteApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BrandApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiBrandsBrandDomainsGetSubresource
     *
     * Retrieves the collection of Branddomain resources..
     *
     */
    public function testApiBrandsBrandDomainsGetSubresource()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBrandCollection
     *
     * Retrieves the collection of BrandOutputDto resources..
     *
     */
    public function testGetBrandCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBrandItem
     *
     * Retrieves a BrandOutputDto resource..
     *
     */
    public function testGetBrandItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchBrandItem
     *
     * Updates the Brand resource..
     *
     */
    public function testPatchBrandItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
