<?php
/**
 * BranddomainApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EmonsiteApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API E-monsite
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: alpha
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace EmonsiteApi;

use EmonsiteApi\Configuration;
use EmonsiteApi\ApiException;
use EmonsiteApi\ObjectSerializer;

/**
 * BranddomainApiTest Class Doc Comment
 *
 * @category Class
 * @package  EmonsiteApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BranddomainApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiBrandsBrandDomainsGetSubresource
     *
     * Retrieves the collection of Branddomain resources..
     *
     */
    public function testApiBrandsBrandDomainsGetSubresource()
    {
    }

    /**
     * Test case for getBranddomainCollection
     *
     * Retrieves the collection of BranddomainOutputDto resources..
     *
     */
    public function testGetBranddomainCollection()
    {
    }

    /**
     * Test case for getBranddomainItem
     *
     * Retrieves a BranddomainOutputDto resource..
     *
     */
    public function testGetBranddomainItem()
    {
    }
}
